version: 2
jobs:
  build_jsnark_circuit_builder:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get jsnark"
          command: git submodule update --init --recursive jsnark
      - run:
          name: "Build JsnarkCircuitBuilder"
          command: |
            cd jsnark/JsnarkCircuitBuilder
            mkdir -p bin
            javac -d bin -cp /usr/share/java/junit4.jar:/bcprov-jdk15on-159.jar  $(find ./src/* | grep ".java$")
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/JsnarkCircuitBuilder/bin
            - jsnark/JsnarkCircuitBuilder/config.properties

  build_jsnark_libsnark:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get jsnark"
          command: git submodule update --init --recursive jsnark
      - run:
          name: "Prepare depends"
          command: |
            cd jsnark/libsnark
            ./prepare-depends.sh
      - run:
          name: "make"
          command: |
            cd jsnark/libsnark
            make
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/libsnark

  build_ethsnarks:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get ethsnarks"
          command: git submodule update --init --recursive ethsnarks
      - run:
          name: "CMake"
          command: |
            cd ethsnarks
            mkdir build
            cd build
            cmake ..
      - run:
          name: "make"
          command: |
            cd ethsnarks/build
            make pinocchio
      - persist_to_workspace:
          root: .
          paths:
            - ethsnarks/bin

  build_jsnark_circuit_builder:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "npm install"
          command: |
            cd ethereum/js
            npm i
      - persist_to_workspace:
          root: .
          paths:
            - ethereum

  simple_example_prove:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "jsnark"
          command: |
            cd jsnark/JsnarkCircuitBuilder
            java -cp bin examples.generators.SimpleCircuitGenerator
      - run:
          name: "ethsnarks: genkeys"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith genkeys pk.raw vk.json
      - run:
          name: "ethsnarks: prove"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith prove jsnark/JsnarkCircuitBuilder/simple_example.in pk.raw proof.json
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/JsnarkCircuitBuilder/simple_example.arith
            - vk.json
            - proof.json

  simple_example_verify_ethsnarks:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "ethsnarks: verify"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith verify vk.json proof.json

  simple_example_verify_ethereum:
    docker:
      - image: appliedblockchain/jsnark-env
      - image: parity/parity:stable
        command: --config dev --jsonrpc-interface all --gasprice 0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Verify on Ethereum"
          command: node ethereum/js/run.js vk.json proof.json


workflows:
  version: 2
  main:
    jobs:
      - build_jsnark_circuit_builder
      - build_jsnark_libsnark
      - build_ethsnarks
      - build_js
      - simple_example_prove:
          requires:
            - build_jsnark_circuit_builder
            - build_jsnark_libsnark
            - build_ethsnarks
      - simple_example_verify_ethsnarks:
          requires:
            - simple_example_prove
      - simple_example_verify_ethereum:
          requires:
            - build_js
            - simple_example_prove
