version: 2
jobs:
  bld_jsnark_circuit_builder:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get jsnark"
          command: git submodule update --init --recursive jsnark
      - run:
          name: "Build JsnarkCircuitBuilder"
          command: |
            cd jsnark/JsnarkCircuitBuilder
            mkdir -p bin
            javac -d bin -cp /usr/share/java/junit4.jar:/bcprov-jdk15on-159.jar  $(find ./src/* | grep ".java$")
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/JsnarkCircuitBuilder/bin
            - jsnark/JsnarkCircuitBuilder/config.properties

  bld_jsnark_libsnark:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get jsnark"
          command: git submodule update --init --recursive jsnark
      - run:
          name: "Prepare depends"
          command: |
            cd jsnark/libsnark
            ./prepare-depends.sh
      - run:
          name: "make"
          command: |
            cd jsnark/libsnark
            make
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/libsnark

  bld_ethsnarks:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "Get ethsnarks"
          command: git submodule update --init --recursive ethsnarks
      - run:
          name: "CMake"
          command: |
            cd ethsnarks
            mkdir build
            cd build
            cmake ..
      - run:
          name: "make"
          command: |
            cd ethsnarks/build
            make pinocchio
      - persist_to_workspace:
          root: .
          paths:
            - ethsnarks/bin

  install_js_deps:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - checkout
      - run:
          name: "npm install"
          command: |
            cd ethereum/js
            npm i
      - persist_to_workspace:
          root: .
          paths:
            - ethereum

  simple_prove:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "jsnark"
          command: |
            cd jsnark/JsnarkCircuitBuilder
            java -cp bin examples.generators.SimpleCircuitGenerator
      - run:
          name: "ethsnarks: genkeys"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith genkeys pk.raw vk.json
      - run:
          name: "ethsnarks: prove"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith prove jsnark/JsnarkCircuitBuilder/simple_example.in pk.raw proof.json
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/JsnarkCircuitBuilder/simple_example.arith
            - vk.json
            - proof.json

  simple_verify_ethsnarks:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "ethsnarks: verify"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/simple_example.arith verify vk.json proof.json
  simple_verify_ethereum:
    docker:
      - image: appliedblockchain/jsnark-env
      - image: parity/parity:stable
        command: --config dev --jsonrpc-interface all --gasprice 0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Verify on Ethereum"
          command: node ethereum/js/run.js $PWD/vk.json $PWD/proof.json

  sha_256_prove:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "jsnark"
          command: |
            cd jsnark/JsnarkCircuitBuilder
            java -cp bin examples.generators.hash.SHA2CircuitGenerator
      - run:
          name: "ethsnarks: genkeys"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/sha_256.arith genkeys sha_256_pk.raw sha_256_vk.json
      - run:
          name: "ethsnarks: prove"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/sha_256.arith prove jsnark/JsnarkCircuitBuilder/sha_256.in sha_256_pk.raw sha_256_proof.json
      - persist_to_workspace:
          root: .
          paths:
            - jsnark/JsnarkCircuitBuilder/sha_256.arith
            - sha_256_vk.json
            - sha_256_proof.json

  sha_256_verify_ethsnarks:
    docker:
      - image: appliedblockchain/jsnark-env
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "ethsnarks: verify"
          command: ethsnarks/bin/pinocchio jsnark/JsnarkCircuitBuilder/sha_256_example.arith verify sha_256_vk.json sha_256_proof.json

  sha_256_verify_ethereum:
    docker:
      - image: appliedblockchain/jsnark-env
      - image: parity/parity:stable
        command: --config dev --jsonrpc-interface all --gasprice 0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Verify on Ethereum"
          command: node ethereum/js/run.js $PWD/sha_256_vk.json $PWD/sha_256_proof.json

workflows:
  version: 2
  main:
    jobs:
      - bld_jsnark_circuit_builder
      - bld_jsnark_libsnark
      - bld_ethsnarks
      - install_js_deps
      - simple_prove:
          requires:
            - bld_jsnark_circuit_builder
            - bld_jsnark_libsnark
            - bld_ethsnarks
      - simple_verify_ethsnarks:
          requires:
            - simple_prove
      - simple_verify_ethereum:
          requires:
            - install_js_deps
            - simple_prove
      - sha_256_prove:
          requires:
            - bld_jsnark_circuit_builder
            - bld_jsnark_libsnark
            - bld_ethsnarks
      - sha_256_verify_ethsnarks:
          requires:
            - sha_256_prove
      - sha_256_verify_ethereum:
          requires:
            - install_js_deps
            - sha_256_prove
