version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: "Get jsnark"
          command: |
            git submodule update --init --recursive jsnark
